// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"database/sql"
	"github.com/ZAF07/tigerlily-e-bakery-inventories/internal/config"
	"github.com/ZAF07/tigerlily-e-bakery-inventories/internal/injection/providers"
)

// Injectors from wire.go:

func LoadGeneralConfig() *config.GeneralConfig {
	generalConfig := providers.GeneralConfigProvider()
	return generalConfig
}

func GetPostgresCredentials() string {
	string2 := providers.PostgresConnectionStringProvider()
	return string2
}

func GetPostgresDBInstance() *sql.DB {
	db := providers.PostgresDBProvider()
	return db
}
