environment: local
application_port: 8000

cors_allow_origin:
  - "http://localhost:8080"

postgres_db:
  environment: local
  port: 5432
  host: localhost
  user: zaffere
  password: ""
  name: tigerlily
  ssl: disable
  max_conns: 50