// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	// "strconv"

	// "github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	// "github.com/volatiletech/sqlboiler/v4/boil"
	// "github.com/volatiletech/sqlboiler/v4/queries"
	// "github.com/volatiletech/sqlboiler/v4/queries/qm"
	// "github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	// "github.com/volatiletech/strmangle"
)

// Customer is an object representing the database table.
type Customer struct {
	ID          int32     `gorm:"column:id"`
	CustomerID  string    `gorm:"column:customer_id"`
	Name        string    `gorm:"column:name"`
	Email       string    `gorm:"column:email"`
	PhoneNumber string    `gorm:"column:phone_number"`
	CreatedAt   null.Time `gorm:"column:created_at"`
	UpdatedAt   null.Time `gorm:"column:updated_at"`
	DeletedAt   null.Time `gorm:"column:deleted_at"`
}
