// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"time"
)

// Discount is an object representing the database table.
type Discount struct {
	ID           int32             `gorm:"column:id"`
	DiscountID   string            `gorm:"column:discount_id"`
	Amount       float64 					`gorm:"column:amount"`
	DiscountCode string            `gorm:"column:discount_code"`
	Description  string            `gorm:"column:description"`
	CreatedAt   	time.Time         `gorm:"column:created_at"`
	UpdatedAt   	time.Time         `gorm:"column:updated_at"`
	DeletedAt   	time.Time         `gorm:"column:deleted_at"`
}
