// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"time"
)

// Skus is an object representing the database table.
type Skus struct {
	ID          int32             `gorm:"column:id"`
	SkuID       string            `gorm:"column:sku_id"`
	Name        string            `gorm:"column:name"`
	Price       float64 					`gorm:"column:price"`
	Type        string            `gorm:"column:type"`
	Description string            `gorm:"column:description"`
	ImageURL    string            `gorm:"column:image_url"`
	CreatedAt   time.Time         `gorm:"column:created_at"`
	UpdatedAt   time.Time         `gorm:"column:updated_at"`
	DeletedAt   time.Time         `gorm:"column:deleted_at"`
}
